apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: ap-south-1

vpc:
  id: vpc-0464fc57cf1868ca8
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-03f5795d93fa299da
      my-new-stack-PublicSubnet02:
        id: subnet-0ee3dca6c62224391
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-0a0c86486a5f1d476
      my-new-stack-PrivateSubnet02:
        id: subnet-01879873505ea8ab5

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.micro
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true